FROM node:22-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 3000

# Comando definido no docker-compose (evita SELinux bloquear scripts montados)
CMD ["npm", "run", "dev"]
